src = files(
    # com.traneptora.jxlatte
    'main/java/com/traneptora/jxlatte/JXLatte.java',
    'main/java/com/traneptora/jxlatte/JXLCodestreamDecoder.java',
    'main/java/com/traneptora/jxlatte/JXLDecoder.java',
    'main/java/com/traneptora/jxlatte/JXLImage.java',
    'main/java/com/traneptora/jxlatte/JXLOptions.java',

    # com.traneptora.jxlatte.bundle
    'main/java/com/traneptora/jxlatte/bundle/AnimationHeader.java',
    'main/java/com/traneptora/jxlatte/bundle/BitDepthHeader.java',
    'main/java/com/traneptora/jxlatte/bundle/BlendingInfo.java',
    'main/java/com/traneptora/jxlatte/bundle/Extensions.java',
    'main/java/com/traneptora/jxlatte/bundle/ExtraChannelInfo.java',
    'main/java/com/traneptora/jxlatte/bundle/ExtraChannelType.java',
    'main/java/com/traneptora/jxlatte/bundle/ImageHeader.java',
    'main/java/com/traneptora/jxlatte/bundle/PassesInfo.java',

    # com.traneptora.jxlatte.color
    'main/java/com/traneptora/jxlatte/color/CIEPrimaries.java',
    'main/java/com/traneptora/jxlatte/color/CIEXY.java',
    'main/java/com/traneptora/jxlatte/color/ColorEncodingBundle.java',
    'main/java/com/traneptora/jxlatte/color/ColorFlags.java',
    'main/java/com/traneptora/jxlatte/color/ColorManagement.java',
    'main/java/com/traneptora/jxlatte/color/GammaTransferFunction.java',
    'main/java/com/traneptora/jxlatte/color/OpsinInverseMatrix.java',
    'main/java/com/traneptora/jxlatte/color/ToneMapping.java',
    'main/java/com/traneptora/jxlatte/color/TransferFunction.java',

    # com.traneptora.jxlatte.entropy
    'main/java/com/traneptora/jxlatte/entropy/ANSSymbolDistribution.java',
    'main/java/com/traneptora/jxlatte/entropy/EntropyState.java',
    'main/java/com/traneptora/jxlatte/entropy/EntropyStream.java',
    'main/java/com/traneptora/jxlatte/entropy/HybridIntegerConfig.java',
    'main/java/com/traneptora/jxlatte/entropy/PrefixSymbolDistribution.java',
    'main/java/com/traneptora/jxlatte/entropy/SymbolDistribution.java',
    'main/java/com/traneptora/jxlatte/entropy/VLCTable.java',
    'main/java/com/traneptora/jxlatte/entropy/VLCTableEntry.java',

    # com.traneptora.jxlatte.frame
    'main/java/com/traneptora/jxlatte/frame/Frame.java',
    'main/java/com/traneptora/jxlatte/frame/FrameFlags.java',
    'main/java/com/traneptora/jxlatte/frame/FrameHeader.java',
    'main/java/com/traneptora/jxlatte/frame/LFGlobal.java',

    # com.traneptora.jxlatte.frame.features
    'main/java/com/traneptora/jxlatte/frame/features/Patch.java',
    'main/java/com/traneptora/jxlatte/frame/features/RestorationFilter.java',
    'main/java/com/traneptora/jxlatte/frame/features/XorShiro.java',

    # com.traneptora.jxlatte.frame.features.spline
    'main/java/com/traneptora/jxlatte/frame/features/spline/Spline.java',
    'main/java/com/traneptora/jxlatte/frame/features/spline/SplineArc.java',
    'main/java/com/traneptora/jxlatte/frame/features/spline/SplinesBundle.java',

    # com.traneptora.jxlatte.frame.group
    'main/java/com/traneptora/jxlatte/frame/group/LFGroup.java',
    'main/java/com/traneptora/jxlatte/frame/group/Pass.java',
    'main/java/com/traneptora/jxlatte/frame/group/PassGroup.java',

    # com.traneptora.jxlatte.frame.modular
    'main/java/com/traneptora/jxlatte/frame/modular/MATree.java',
    'main/java/com/traneptora/jxlatte/frame/modular/ModularChannel.java',
    'main/java/com/traneptora/jxlatte/frame/modular/ModularStream.java',
    'main/java/com/traneptora/jxlatte/frame/modular/SqueezeParam.java',
    'main/java/com/traneptora/jxlatte/frame/modular/TransformInfo.java',
    'main/java/com/traneptora/jxlatte/frame/modular/WPParams.java',

    # com.traneptora.jxlatte.frame.vardct
    'main/java/com/traneptora/jxlatte/frame/vardct/DCTParams.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/HFBlockContext.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/HFCoefficients.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/HFGlobal.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/HFMetadata.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/HFPass.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/LFChannelCorrelation.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/LFCoefficients.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/LLFScale.java',
    'main/java/com/traneptora/jxlatte/frame/vardct/TransformType.java',

    # com.traneptora.jxlatte.io
    'main/java/com/traneptora/jxlatte/io/Bitreader.java',
    'main/java/com/traneptora/jxlatte/io/Demuxer.java',
    'main/java/com/traneptora/jxlatte/io/InvalidBitstreamException.java',
    'main/java/com/traneptora/jxlatte/io/IOHelper.java',
    'main/java/com/traneptora/jxlatte/io/Loggers.java',
    'main/java/com/traneptora/jxlatte/io/PFMWriter.java',
    'main/java/com/traneptora/jxlatte/io/PNGWriter.java',
    'main/java/com/traneptora/jxlatte/io/PushbackInputStream.java',

    # com.traneptora.jxlatte.util
    'main/java/com/traneptora/jxlatte/util/Dimension.java',
    'main/java/com/traneptora/jxlatte/util/ImageBuffer.java',
    'main/java/com/traneptora/jxlatte/util/MathHelper.java',
    'main/java/com/traneptora/jxlatte/util/Point.java',
    'main/java/com/traneptora/jxlatte/util/Rectangle.java',

    # com.traneptora.jxlatte.util.functional
    'main/java/com/traneptora/jxlatte/util/functional/ExceptionalConsumer.java',
    'main/java/com/traneptora/jxlatte/util/functional/ExceptionalRunnable.java',
    'main/java/com/traneptora/jxlatte/util/functional/ExceptionalSupplier.java',
    'main/java/com/traneptora/jxlatte/util/functional/FloatUnaryOperator.java',
    'main/java/com/traneptora/jxlatte/util/functional/FunctionalHelper.java',
)

res = structured_sources(
    files(
        'main/resources/bt2020-d65-pq.icc.zz',
        'main/resources/bt709-d65-srgb.icc.zz',
    ),
)

jxlatte_jar = jar('jxlatte',
    sources: src,
    java_resources: res,
    main_class: 'com.traneptora.jxlatte.JXLatte',
)
